# Generated by Django 2.1.4 on 2019-10-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prof',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='prof',
            name='web',
            field=models.TextField(),
        ),
    ]
