# Generated by Django 2.2.1 on 2019-10-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profs', '0003_auto_20191024_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='aor',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='prof',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prof',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prof',
            name='web',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
