# Generated by Django 2.2.1 on 2019-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profs', '0004_auto_20191025_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='phone',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
